version: '3.9'

networks:
  proxy:
    name: proxy
    external: true

services:
  traefik:
    restart: unless-stopped
    image: traefik:v2.0.2
    container_name: traefik_hub_symfony
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    labels:
      - "traefik.http.services.traefik.loadbalancer.server.port=8090"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.gkbook.acme.tlschallenge=true"
      # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.gkbook.acme.email=elhadibeddarem@gmail.com"
      - "--certificatesresolvers.gkbook.acme.storage=/letsencrypt/acme.json"
    volumes:
      - ./letsencrypt:/letsencrypt
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./tls.yml:/etc/traefik/tls.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - certs:/etc/ssl/traefik
    networks:
      - proxy

  reverse-proxy-https-helper:
    image: alpine
    container_name: www_reverse_proxy
    command: sh -c "cd /etc/ssl/traefik && wget traefik.me/cert.pem -O cert.pem && wget traefik.me/privkey.pem -O privkey.pem"
    volumes:
      - certs:/etc/ssl/traefik
    networks:
      - proxy 

  whoami:
    # A container that exposes an API to show its IP address
    image: containous/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.traefik.me`)"
    networks:
      - proxy

  db:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    container_name: db_geekbook_app
    restart: always
    environment:
      POSTGRES_DB: geekbook
      # You should definitely change the password in production
      POSTGRES_PASSWORD: H#isoka44
      POSTGRES_USER: killua
    volumes:
      - database_data:/var/www/html/postgresql/data:rw
    networks:
      - proxy

  gkbook:
    build: docker
    image: gkbook
    container_name: www_geekbook_app
    environment:
      POSTGRES_PASSWORD: H#isoka44
      POSTGRES_USER: killua
      POSTGRES_DB: geekbook
    labels:
      - "traefik.http.routers.gkbook.rule=Host(`gkbook.traefik.me`)"
      - "traefik.http.routers.gkbook-tls.tls.domains[0].main=gkbook.traefik.me"
      - "traefik.http.routers.gkbook-tls.tls.domains[0].sans=gkbook-*.traefik.me"
      - "traefik.http.routers.gkbook.tls=true"
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www/html
    restart: always
    networks:
      - proxy
    depends_on:
      - db
      - meilisearch

  apache:
    image: httpd:2.4
    container_name: apache
    volumes:
      - ./docker/vhosts/default-ssl.conf:/usr/local/apache2/conf.d/default-ssl.conf
      - ./ssl:/usr/local/apache2/ssl
      - ./html:/var/www/html
    depends_on:
      - whoami
      - db
      - traefik
    networks:
      - proxy

  mailer:
    image: schickling/mailcatcher
    networks:
      - proxy 
      # vérifier le port 1080

  meilisearch:
    image: getmeili/meilisearch:${MEILISEARCH_VERSION:-latest}
    container_name: meilisearch
    restart: always
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY:-!ChangeMe!}
    volumes:
      - ./meilisearch_data:/meili_data
    networks:
      - proxy

  mercure:
    image: dunglas/mercure
    command: caddy run -config /var/www/etc/caddy/Caddyfile.dev
    environment:
        SERVER_NAME: ':7001'
        MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
        MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
    volumes:
      - mercure_data:/data
      - mercure_config:/config
    networks:
      - proxy

volumes:
  database_data:
  meilisearch_data:
  certs:
  mercure_data:
  mercure_config: