networks:
  proxy:
    name: proxy
    external: true

services:
  traefik:
    restart: unless-stopped
    image: traefik:v2.0.2
    container_name: traefik_hub_symfony
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    labels:
      - "traefik.http.services.traefik.loadbalancer.server.port=8090"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.gkbook.acme.tlschallenge=true"
      # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.gkbook.acme.email=elhadibeddarem@gmail.com"
      - "--certificatesresolvers.gkbook.acme.storage=/letsencrypt/acme.json"
    volumes:
      - ./letsencrypt:/letsencrypt
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./tls.yml:/etc/traefik/tls.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - certs:/etc/ssl/traefik
    networks:
      - proxy

  reverse-proxy-https-helper:
    image: alpine
    container_name: www_reverse_proxy
    command: sh -c "cd /etc/ssl/traefik && wget traefik.me/cert.pem -O cert.pem && wget traefik.me/privkey.pem -O privkey.pem"
    volumes:
      - certs:/etc/ssl/traefik
    networks:
      - proxy 

  whoami:
    # A container that exposes an API to show its IP address
    image: containous/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.traefik.me`)"
    networks:
      - proxy

  db:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    container_name: db_geekbook_app
    restart: always
    environment:
      POSTGRES_DB: geekbook
      # You should definitely change the password in production
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_USER: postgres
    volumes:
      - database_data:/var/www/html/postgresql/data:rw
    networks:
      - proxy

  gkbook:
    build: docker
    image: gkbook
    container_name: www_geekbook_app
    environment:
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_USER: postgres
      POSTGRES_DB: geekbook
    labels:
      - "traefik.http.routers.gkbook.rule=Host(`gkbook.traefik.me`)"
      - "traefik.http.routers.gkbook-tls.tls.domains[0].main=gkbook.traefik.me"
      - "traefik.http.routers.gkbook-tls.tls.domains[0].sans=gkbook-*.traefik.me"
      - "traefik.http.routers.gkbook.tls=true"
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www/html
    restart: always
    networks:
      - proxy
    depends_on:
      - db
      - meilisearch

  apache:
    image: httpd:2.4
    container_name: apache
    volumes:
      - ./docker/vhosts/default-ssl.conf:/usr/local/apache2/conf.d/default-ssl.conf
      - ./ssl:/usr/local/apache2/ssl
      - ./html:/var/www/html
    depends_on:
      - whoami
      - db
      - traefik
    networks:
      - proxy

  mailer:
    image: schickling/mailcatcher
    container_name: www_meiler_app
    ports:
      - "1025:1080"
    networks:
      - proxy 

###> meilisearch/search-bundle ###
  meilisearch:
    image: getmeili/meilisearch:${MEILISEARCH_VERSION:-v1.0}
    container_name: meilisearch_db_app
    environment:
      # You should definitely change the master key in production
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY:-7Twsnmr-TYZcIuISSxDMJXeb6WUHjjOZwKBE73CzYBo}
    ports:
      - "7800:7700"
    volumes:
      - meilisearch_data:/meili_data
    networks:
      - proxy
###< meilisearch/search-bundle ###

  ###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    container_name: www_mercure_app
    restart: unless-stopped
    environment:
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins https://gkbook.traefik.me
    ports:
      - "8888:80"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - proxy
###< symfony/mercure-bundle ###
  caddy:
    image: abiosoft/caddy
    container_name: caddy
    volumes:
      - './caddy/Caddyfile/Caddyfile.dev:/etc/caddy/Caddyfile'
      - './src:/srv'
      - './caddy:/root/.caddy'
    networks:
      - proxy

volumes:
  database_data:
  meilisearch_data:
  certs:
  caddy_data:
  caddy_config: