logLevel: INFO

api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  file:
    filename: /etc/traefik
  docker:
    endpoint: unix:///var/run/docker.sock
    useBindPortIP: true
    watch: true
    exposedByDefault: true
    defaultRule: "HostRegexp(`{{ index .Labels \"com.docker.compose.service\"}}.traefik.me`,`{{ index .Labels \"com.docker.compose.service\"}}-{dashed-ip:.*}.traefik.me`)"

certificatesResolvers:
  myresolver:
    acme:
      email: elhadibeddarem@gmail.com
      storage: "acme.json"
      httpChallenge:
        entryPoint: web