# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    csrf_protection: true
    http_method_override: true
    handle_all_throwables: true
    disallow_search_engine_index: false
    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        #handler_id: '%env(REDIS_URL)%'
        handler_id: '%env(REDIS_URL)%'
        save_path: "unix:///var/run/redis/redis.sock?persistent=1&weight=1&database=0"
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
