parameters:

services: 
    # default configuration for services in *this* file
  _defaults:
      autowire: true      # Automatically injects dependencies in your services.
      autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    
  Liip\Acme\Tests\App\DataFixtures\ORM\: 
      resource: 'DataFixtures/ORM/*' 
      tags: ['doctrine.fixture.orm']
