name: Pipeline-CI
on:
  push:
    branches: [ main ]
env:
  IMAGE_NAME: duncanidaho/geekbook
jobs: 
  ci:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v2

      - name: Setup PHP Action
        # You may pin to the exact commit or the version.
        # uses: shivammathur/setup-php@a4e22b60bbb9c1021113f2860347b0759f66fe5d
        uses: shivammathur/setup-php@2.30.0
        with:
          # Setup PHP extensions.
          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_pgsql, dom, filter, gd, json

      - name: Cache
        uses: actions/cache@v4.0.1
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: |
            vendor
          # An explicit key for restoring and saving the cache
          key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}

      - name: Docker Setup Buildx
        # You may pin to the exact commit or the version.
        # uses: docker/setup-buildx-action@0d103c3126aa41d772a8362f6aa67afac040f80c
        uses: docker/setup-buildx-action@v3.1.0
        
          
        
      -  name: LS
         run: ls
    
